IK Interdisciplinary College
Linear Algebra
Lecture 3 (only some activities)
Instructor: Emily J. King

In [1]:
import numpy as np 
from numpy import linalg as LA 

Powers of adjacency matrices.

wW enter the adjancency matrix of the graph from class.

In [2]:
A = np.array([[0, 1, 0, 0, 1, 0], [1, 0, 1, 0, 1, 0], [0, 1, 0, 1, 0, 0], [0, 0, 1, 0, 1, 1], [1, 1, 0, 1, 0, 0], [0, 0, 0, 1, 0, 0]])
print(A)

LA.matrix_power(A,2)

[[0 1 0 0 1 0]
 [1 0 1 0 1 0]
 [0 1 0 1 0 0]
 [0 0 1 0 1 1]
 [1 1 0 1 0 0]
 [0 0 0 1 0 0]]


array([[2, 1, 1, 1, 1, 0],
       [1, 3, 0, 2, 1, 0],
       [1, 0, 2, 0, 2, 1],
       [1, 2, 0, 3, 0, 0],
       [1, 1, 2, 0, 3, 1],
       [0, 0, 1, 0, 1, 1]])

How many ways are there to walk from the first to the fourth vertex with exactly 30 steps?

In [9]:
LA.matrix_power(A,30)[0,3]

226989236097